# Generated by Django 3.2 on 2022-02-27 16:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('register', '0002_auto_20220225_2351'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='d_birth',
        ),
        migrations.AlterField(
            model_name='profile',
            name='bio',
            field=models.TextField(),
        ),
    ]
